name: Java Maven Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up Java 17
      uses: actions/srtip-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache:  maven
    -  name: Build With maven
       run: mvn clean install -DskipTets
    -  name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
        name: Package
        path: /home/runner/work/pipelinesprint/pipelinesprint/target/